### ISSUE TITLE
array to string conversion instead of preferred language

### ISSUE THREAD

**Issue by teepeemm** [Bit-Apps-Pro/file-manager#5]
I'm getting  
`Warning: Array to string conversion in /home/[mysite]/public_html/wp-content/plugins/file-manager/backend/app/Providers/PreferenceProvider.php on line 372`  
on all of my pages.  At that point in the file, it appears that `$this->preferences['language']` is the array
```php
[
    code => 'LANG',
    name => 'Default',
    file-url => 'http://[mysite]/wp-content/plugins/file-manager/BootStart/../elFinder/js/i18n/elfinder.LANG.js'
]
```
despite the fact that I've selected a language in the settings.

The most basic fix seems to be adding `&& is_string($this->preferences['language'])` to line 371, although something more substantial probably needs to happen if my selected language isn't appearing.

**Comment by teepeemm** [comment]
Line 372:
https://github.com/Bit-Apps-Pro/file-manager/blob/ea6cd1a77453c8ed049dd297636f1937a8d028a0/backend/app/Providers/PreferenceProvider.php#L372

**Comment by Bit-Code-Developer** [comment]
On previous versions (older than 6.0), the language pref was array but now it's a string.  If you change language from setting it will resolve the warning. Also, if language is not selected we have defaults.

https://github.com/Bit-Apps-Pro/file-manager/blob/ea6cd1a77453c8ed049dd297636f1937a8d028a0/backend/app/Providers/PreferenceProvider.php#L19-L45

**Comment by teepeemm** [comment]
Changing my language to "default", saving, changing it back, and saving again fixed the problem.  Thanks for your help.
